name: yellowbrick_test
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib>=1.5.1,!=3.0.0
  - scipy>=1.0.0
  - scikit-learn>=0.20
  - numpy>=1.13.0
  - cycler>=0.10.0
  - pytest>=3.4.1
  - pytest-cov>=2.5.1
  - pytest-flakes>=2.0.0
  - pytest-spec>=1.1.0
  - coverage>=4.4.1
  - requests>=2.18.3
  - six==1.11.0
  - nltk>=3.2
  - pandas>=0.20
  - umap-learn>=0.3
  - sphinx>=1.7.5
  - sphinx_rtd_theme>=0.4.0
  - numpydoc>=0.8.0
  - jupyter
